"""Converting money to numeric field.

Revision ID: 44644b0ef7fe
Revises: 9293ade6aa95
Create Date: 2020-03-04 10:35:30.744695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44644b0ef7fe'
down_revision = '9293ade6aa95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('individual_contribution', 'amount',
               existing_type=postgresql.MONEY(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('individual_contribution', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=postgresql.MONEY(),
               existing_nullable=True)
    # ### end Alembic commands ###
