"""Adding candidates.

Revision ID: 8a13e442ab50
Revises: 
Create Date: 2020-03-02 00:29:56.367704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a13e442ab50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('candidate_fec_id', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('party_affiliation', sa.String(length=3), nullable=True),
    sa.Column('election_year', sa.SmallInteger(), nullable=False),
    sa.Column('office', postgresql.ENUM('H', 'S', name='office'), nullable=False),
    sa.Column('office_state', sa.String(length=2), nullable=False),
    sa.Column('office_district', sa.String(length=2), nullable=True),
    sa.Column('incumbent_challenger_status', postgresql.ENUM('C', 'I', 'O', name='incumbent_challenger_status'), nullable=True),
    sa.Column('principal_campaign_committee_fec_id', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('candidate_fec_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    # ### end Alembic commands ###
