"""Adding committees.

Revision ID: cdd45d821260
Revises: 8a13e442ab50
Create Date: 2020-03-03 00:25:17.310539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdd45d821260'
down_revision = '8a13e442ab50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee',
    sa.Column('committee_id', sa.Integer(), nullable=False),
    sa.Column('committee_fec_id', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('designation', postgresql.ENUM('A', 'B', 'D', 'J', 'P', 'U', name='committee_designation'), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('party_affiliation', sa.String(length=3), nullable=True),
    sa.Column('interest_group_category', postgresql.ENUM('C', 'L', 'M', 'T', 'V', 'W', 'I', 'H', name='interest_group_category'), nullable=True),
    sa.Column('connected_organization', sa.String(), nullable=True),
    sa.Column('candidate_fec_id', sa.String(length=9), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.candidate_id'], ),
    sa.PrimaryKeyConstraint('committee_id'),
    sa.UniqueConstraint('committee_fec_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('committee')
    # ### end Alembic commands ###
