"""Adding flagged employers.

Revision ID: fc6af3722d01
Revises: 44644b0ef7fe
Create Date: 2020-03-07 17:16:03.490884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6af3722d01'
down_revision = '44644b0ef7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flagged_employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('flagged_individual_contributor', sa.Column('flagged_employer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'flagged_individual_contributor', 'flagged_employer', ['flagged_employer_id'], ['id'])
    op.add_column('individual_contributor', sa.Column('employer_flagged_as_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'individual_contributor', 'flagged_employer', ['employer_flagged_as_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'individual_contributor', type_='foreignkey')
    op.drop_column('individual_contributor', 'employer_flagged_as_id')
    op.drop_constraint(None, 'flagged_individual_contributor', type_='foreignkey')
    op.drop_column('flagged_individual_contributor', 'flagged_employer_id')
    op.drop_table('flagged_employer')
    # ### end Alembic commands ###
