"""Adding category to employers.

Revision ID: 105458005ed1
Revises: 25f676d30c10
Create Date: 2020-03-21 15:52:13.031238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105458005ed1'
down_revision = '25f676d30c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flagged_employer', sa.Column('group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flagged_employer', 'group')
    # ### end Alembic commands ###
