"""Adding committee contributions.

Revision ID: 25f676d30c10
Revises: ccea236c1362
Create Date: 2020-03-11 18:02:19.014611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25f676d30c10'
down_revision = 'ccea236c1362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amendment_indicator', postgresql.ENUM('N', 'A', 'T', name='amendment_indicator', create_type=False), nullable=True),
    sa.Column('report_type', sa.String(length=3), nullable=True),
    sa.Column('primary_general_indicator', sa.String(length=5), nullable=True),
    sa.Column('fec_image_ref', sa.String(length=18), nullable=True),
    sa.Column('transaction_type', sa.String(length=3), nullable=True),
    sa.Column('entity_type', sa.String(length=3), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('donor_committee_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('recipient_city', sa.String(length=30), nullable=True),
    sa.Column('recipient_state', sa.String(length=2), nullable=True),
    sa.Column('recipient_zip', sa.String(length=9), nullable=True),
    sa.Column('recipient_occupation', sa.String(length=38), nullable=True),
    sa.Column('recipient_employer', sa.String(length=38), nullable=True),
    sa.Column('other_fec_id', sa.String(length=9), nullable=True),
    sa.Column('candidate_fec_id', sa.String(length=9), nullable=True),
    sa.Column('recipient_committee_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('transaction_fec_id', sa.String(length=32), nullable=True),
    sa.Column('file_num', sa.Numeric(precision=22), nullable=True),
    sa.Column('memo_cd', sa.String(length=1), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('fec_unique_id', sa.Numeric(precision=19), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['donor_committee_id'], ['committee.id'], ),
    sa.ForeignKeyConstraint(['recipient_committee_id'], ['committee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fec_unique_id')
    )
    op.add_column('committee', sa.Column('connected_organization_flagged_as_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'committee', 'flagged_employer', ['connected_organization_flagged_as_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'committee', type_='foreignkey')
    op.drop_column('committee', 'connected_organization_flagged_as_id')
    op.drop_table('committee_contribution')
    # ### end Alembic commands ###
