"""Adding alerts.

Revision ID: 4b50d4e762a5
Revises: bbd8bd6bb1e2
Create Date: 2020-04-08 00:18:01.473715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b50d4e762a5'
down_revision = 'bbd8bd6bb1e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('flagged_committee_contributions', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('flagged_individual_contributions', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    # ### end Alembic commands ###
