"""Adding pledge date.

Revision ID: bbd8bd6bb1e2
Revises: 105458005ed1
Create Date: 2020-04-07 12:20:43.983709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd8bd6bb1e2'
down_revision = '105458005ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('pledge_date', sa.Date(), nullable=True))
    op.drop_index('individual_contributor_name_city_state_zip_employer_occupation_', table_name='individual_contributor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('individual_contributor_name_city_state_zip_employer_occupation_', 'individual_contributor', ['name', 'city', 'state', 'zip', 'employer', 'occupation'], unique=False)
    op.drop_column('candidate', 'pledge_date')
    # ### end Alembic commands ###
