"""Adding index to committee_id.

Revision ID: f6216325fca0
Revises: 254ab76b2903
Create Date: 2020-03-10 12:57:48.641176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6216325fca0'
down_revision = '254ab76b2903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_individual_contribution_committee_id'), 'individual_contribution', ['committee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individual_contribution_committee_id'), table_name='individual_contribution')
    # ### end Alembic commands ###
